[tool.poetry]
name = "vyxalbot2"
version = "0.1.0"
description = ""
authors = ["GingerIndustries <75683114+gingerindustries@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gidgethub = "^5.2.1"
sechat = { git = "https://github.com/GingerIndustries/sechat.git", branch = "v2" }
cachetools = "^5.3.0"

[tool.poetry.group.dev.dependencies]
black = {version = "^23.1.0", allow-prereleases = true}
jwt = {version = "^1.3.1", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
